services:
  frontend:
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    networks:
      - backend_network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - backend_network
    volumes:
      - backend_data:/app/data
    restart: always

volumes:
  backend_data:
    driver: local

networks:
  backend_network:
    driver: bridge